map_planner_node:
  ros__parameters:
    voxel_size: 0.15
    safety_radius: 0.30
    occupancy_pcd_path: map_voxels_with_racks_inflated.pcd
    rack_boxes: [
      4.32, 6.818, 1.88, 6.50, 1.05, 3.76, 0.0,
      4.32, 11.36, 1.88, 6.50, 1.05, 3.76, 0.0
    ]
    allow_diagonal: true
    heuristic_weight: 1.0
    max_planning_time_s: 5.0
    max_expansions: 0
    snap_radius_cells: 0
    simplify_path: true